### ISSUE TITLE
bwrap: Can't mkdir ~/.gnupg/openpgp-revocs.d: Read-only file system thread 'main' panicked at 'Failed to build package', src/wrapped.rs:61:2

### ISSUE THREAD

**Issue by theel0ja** [vn971/rua#5]
```
➜  ~ rua install sound-theme-smooth
Verifying package sound-theme-smooth. [V]=view PKGBUILD, [E]=edit PKGBUILD, [I]=run shell to inspect, [O]=ok, use package: o
bwrap: Can't mkdir /home/eliaso/.gnupg/openpgp-revocs.d: Read-only file system
thread 'main' panicked at 'Failed to build package', src/wrapped.rs:61:2
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: __libc_start_main
  10: <unknown>
```

**Comment by vn971** [comment]
Would you be able to test the newer version (of RUA)?
I've pushed 0.9.5, hopefully it'll fix the error.. I've re-factored that part of the security wrapper.

**Comment by vn971** [comment]
closing as outdated. Please reopen if you'll be able to reproduce the issue on newest RUA.
The current version can be installed with just `cargo install rua`.
