### ISSUE TITLE
Panic on package build failure.

### ISSUE THREAD

**Issue by c-edw** [vn971/rua#6]
I am trying to install some packages and am getting a panic on `src/wrapped.rs:61:2`. The backtrace is pretty unhelpful, but it looks like the command that was being executed didn't return 0. 

Ideally this shouldn't panic, but should just print a warning or error.

**Comment by vn971** [comment]
@c-edw Do you have backtrace at all, or is it just unhelpful? If you're compiling via AUR, you need to uncomment `options+=(!strip)`, because otherwise `makepkg` strips out all debug symbols.

**Comment by vn971** [comment]
@c-edw yes, panicking is indeed not a nice thing to have. I need to make an iteration of cleaning them up again, probably.

By the way, have you installed the dependencies?: https://github.com/vn971/rua#install-dependencies

**Comment by c-edw** [comment]
The first time, I followed `Install (the AUR way)`, which lead to this issue. I've just tried `Install (the Rust way)` but get an immediate panic when trying to install something. I'm the `root` user in a Docker container, if that matters.

```
thread 'main' panicked at 'Failed to git-clone repository wlroots-git: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
   7: rua::aur::fresh_download
   8: rua::wrapped::prefetch_aur
   9: rua::wrapped::install
  10: rua::main
  11: std::rt::lang_start::{{closure}}
  12: main
  13: __libc_start_main
  14: _start
```

**Comment by c-edw** [comment]
I have installed the dependencies also.

**Comment by vn971** [comment]
I see that it's in `rua::aur:fresh_download` then.
I'll check this method, as well as other usages of `unwrap` that I have.
Big thanks with the report! I'll try to come back on it very soon or during next day.

**Comment by vn971** [comment]
@c-edw it actually seems as though `git` is unavailable inside your OS. Could that be true? I was pretty sure `git` is part of the `base-devel` package, but maybe it's not?

**Comment by vn971** [comment]
@c-edw this one is from `bwrap` -- the security sandbox the project uses: https://github.com/projectatomic/bubblewrap
I wonder if you'll have the error while running from non-root. This needs some thinking-upon. The issue itself is basically outside of RUA totally.

On the other hand, people say that running bubblewrap inside docker works at least partly:https://github.com/projectatomic/bubblewrap/issues/284
so there probably _is_ something we can do.

**Comment by vn971** [comment]
Thanks!

**Comment by c-edw** [comment]
I have tried installing with rua under an unprivileged user, which gives a different error:

```
bwrap: capset failed: Operation not permitted
thread 'main' panicked at 'Failed to build package', /home/cedwards/.cargo/registry/src/github.com-1ecc6299db9ec823/rua-0.9.10/src/wrapped.rs:61:2
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:211
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::begin_panic
   4: rua::wrapped::build_directory
   5: rua::wrapped::install
   6: rua::main
   7: std::rt::lang_start::{{closure}}
   8: main
   9: __libc_start_main
  10: _start
```

This is when running with `RUST_BACKTRACE=1 .cargo/bin/rua install wlroots-git`. If I run it with `sudo`, it gives the same error as when it was run under root.

If you'd like, I can report this on bubblewrap.

**Comment by vn971** [comment]
@c-edw Apparently "bubblewrap" needs some rights to prepare the jail, which docker lacks by default. This issue describes the very same problem I think: https://github.com/flatpak/flatpak/issues/1326

**Comment by vn971** [comment]
I've installed docker with an Arch image, the problem is totally reproducible.
The easiest way to repro the issue is to just invoke bubblewrap directly:
`bwrap --dev-bind / / bash`

**Comment by vn971** [comment]
UPDATED ^

**Comment by c-edw** [comment]
Does `rua` support package building without the bubblewrap jail? Maybe you could somehow detect if being run inside a Docker container? 

Unfortunately I don't run Arch on my root system, and I was using the container to test various AUR helpers.

**Comment by vn971** [comment]
@c-edw Automatic disabling of security properties is something that I'd rather avoid, even if program thinks it runs inside docker. An explicit argument is possible though. I'll take some time on this.

**Comment by c-edw** [comment]
But helpers such as `yay` don't building inside a jail, right? Of course, the security feature is nice, but it's not a disaster if disabled.

**Comment by vn971** [comment]
UPDATED ^

**Comment by vn971** [comment]
For the record, `rua` will now fail-fast if it sees that the security jail cannot be launched. It will also explain the situation explicitly.

Commands that do not require the jail, like `rua search`, `rua info`, `rua upgrade --printonly`, can be run just fine.

**Comment by cedws** [comment]
Thanks, I will take another look at this project when I get the opportunity.

**Comment by gwpl** [comment]
How to use CLI override described in https://github.com/vn971/rua/issues/6#issuecomment-442998828 ?
I can't find examples in `README.md` nor `docs/` or `rua --help` or `rua intall --help`.
